// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {model} from '../models';

export function AddDocuments():Promise<main.AddDocumentsResult>;

export function AddTagToDocument(arg1:string,arg2:string):Promise<Array<model.Tag>>;

export function CreateAgentSession(arg1:string,arg2:string,arg3:string,arg4:string):Promise<model.AgentSession>;

export function CreateFolder(arg1:string,arg2:string):Promise<model.Folder>;

export function CreateTag(arg1:string,arg2:string):Promise<model.Tag>;

export function DeleteAgentSession(arg1:string):Promise<void>;

export function DeleteDocument(arg1:string):Promise<void>;

export function DeleteFolder(arg1:string):Promise<void>;

export function DeleteTag(arg1:string):Promise<void>;

export function GetDocument(arg1:string):Promise<main.DocumentDetail>;

export function IngestURLs(arg1:Array<string>,arg2:boolean,arg3:number,arg4:number):Promise<main.IngestResult>;

export function ListAgentMessages(arg1:string):Promise<Array<model.AgentMessage>>;

export function ListAgentSessions():Promise<Array<model.AgentSession>>;

export function ListDocuments(arg1:number,arg2:number,arg3:string):Promise<main.DocumentsPage>;

export function ListFolders(arg1:string):Promise<Array<model.Folder>>;

export function ListTags():Promise<Array<model.Tag>>;

export function MoveDocument(arg1:string,arg2:string):Promise<void>;

export function Ping():Promise<string>;

export function ProcessDocument(arg1:string):Promise<void>;

export function RefreshDocument(arg1:string):Promise<model.Document>;

export function RemoveTagFromDocument(arg1:string,arg2:string):Promise<Array<model.Tag>>;

export function Search(arg1:string,arg2:number,arg3:number,arg4:string,arg5:string):Promise<main.SearchResponse>;

export function SendAgentMessage(arg1:string,arg2:string,arg3:string):Promise<void>;
