// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddDocuments() {
  return window['go']['main']['App']['AddDocuments']();
}

export function AddTagToDocument(arg1, arg2) {
  return window['go']['main']['App']['AddTagToDocument'](arg1, arg2);
}

export function CreateAgentSession(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateAgentSession'](arg1, arg2, arg3, arg4);
}

export function CreateFolder(arg1, arg2) {
  return window['go']['main']['App']['CreateFolder'](arg1, arg2);
}

export function CreateTag(arg1, arg2) {
  return window['go']['main']['App']['CreateTag'](arg1, arg2);
}

export function DeleteAgentSession(arg1) {
  return window['go']['main']['App']['DeleteAgentSession'](arg1);
}

export function DeleteDocument(arg1) {
  return window['go']['main']['App']['DeleteDocument'](arg1);
}

export function DeleteFolder(arg1) {
  return window['go']['main']['App']['DeleteFolder'](arg1);
}

export function DeleteTag(arg1) {
  return window['go']['main']['App']['DeleteTag'](arg1);
}

export function GetDocument(arg1) {
  return window['go']['main']['App']['GetDocument'](arg1);
}

export function IngestURLs(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['IngestURLs'](arg1, arg2, arg3, arg4);
}

export function ListAgentMessages(arg1) {
  return window['go']['main']['App']['ListAgentMessages'](arg1);
}

export function ListAgentSessions() {
  return window['go']['main']['App']['ListAgentSessions']();
}

export function ListDocuments(arg1, arg2, arg3) {
  return window['go']['main']['App']['ListDocuments'](arg1, arg2, arg3);
}

export function ListFolders(arg1) {
  return window['go']['main']['App']['ListFolders'](arg1);
}

export function ListTags() {
  return window['go']['main']['App']['ListTags']();
}

export function MoveDocument(arg1, arg2) {
  return window['go']['main']['App']['MoveDocument'](arg1, arg2);
}

export function Ping() {
  return window['go']['main']['App']['Ping']();
}

export function ProcessDocument(arg1) {
  return window['go']['main']['App']['ProcessDocument'](arg1);
}

export function RefreshDocument(arg1) {
  return window['go']['main']['App']['RefreshDocument'](arg1);
}

export function RemoveTagFromDocument(arg1, arg2) {
  return window['go']['main']['App']['RemoveTagFromDocument'](arg1, arg2);
}

export function Search(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['Search'](arg1, arg2, arg3, arg4, arg5);
}

export function SendAgentMessage(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendAgentMessage'](arg1, arg2, arg3);
}
